// frontend/src/routes/my-playlists/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { fetchApi } from '#lib/api';
	import { ListVideo, Plus, Trash2, Edit } from 'lucide-svelte';

	let playlists: any[] = $state([]);
	let isLoading = $state(true);
	let error = $state('');
	
	let isCreating = $state(false);
	let newPlaylistName = $state('');

	async function loadPlaylists() {
		isLoading = true;
		error = '';
		try {
			const res = await fetchApi('/playlists');
			playlists = res.playlists || res.data || [];
			
			playlists.forEach(async (playlist, index) => {
				try {
					const details = await fetchApi(`/playlists/${playlist.id}`);
					if (details && details.videos) {
						playlists[index] = { ...playlist, videoCount: details.videos.length };
					}
				} catch (e) {
					// Ignore
				}
			});
		} catch (err: any) {
			error = err.message || 'Failed to load playlists.';
		} finally {
			isLoading = false;
		}
	}

	onMount(() => {
		loadPlaylists();
	});

	async function handleCreatePlaylist(e: Event) {
		e.preventDefault();
		if (!newPlaylistName.trim()) return;

		try {
			const res = await fetchApi('/playlists', {
				method: 'POST',
				body: JSON.stringify({ title: newPlaylistName.trim() })
			});
			
			// Refresh list or optimistic update
			if (res.playlist) {
				playlists = [res.playlist, ...playlists];
			} else {
				await loadPlaylists();
			}
			
			newPlaylistName = '';
			isCreating = false;
		} catch (err: any) {
			alert('Failed to create playlist');
		}
	}

	async function handleDelete(id: string | number) {
		if (!confirm('Are you sure you want to delete this playlist?')) return;
		try {
			await fetchApi(`/playlists/${id}`, { method: 'DELETE' });
			playlists = playlists.filter(p => p.id !== id);
		} catch (err) {
			alert('Failed to delete playlist');
		}
	}
</script>

<svelte:head>
	<title>My Playlists - Aurahub</title>
</svelte:head>

<div class="space-y-6 max-w-6xl mx-auto">
	<div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b">
		<h1 class="text-2xl font-bold tracking-tight">My Playlists</h1>
		<button 
			onclick={() => isCreating = !isCreating}
			class="inline-flex items-center justify-center rounded-full bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 text-sm font-medium transition-colors"
		>
			<Plus class="w-4 h-4 mr-2" />
			New Playlist
		</button>
	</div>

	{#if isCreating}
		<div class="bg-card border rounded-xl p-6 shadow-sm mb-6 max-w-md animate-in slide-in-from-top-2">
			<h3 class="font-semibold text-lg mb-4">Create New Playlist</h3>
			<form onsubmit={handleCreatePlaylist} class="space-y-4">
				<div>
					<label for="name" class="block text-sm font-medium mb-1">Name</label>
					<input 
						id="name" 
						type="text" 
						bind:value={newPlaylistName} 
						placeholder="e.g., Summer Vibes 2024"
						class="w-full bg-background border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/50"
						required
					/>
				</div>
				<div class="flex justify-end gap-2">
					<button 
						type="button" 
						onclick={() => {isCreating = false; newPlaylistName = '';}}
						class="px-4 py-2 text-sm font-medium rounded-lg hover:bg-muted transition-colors"
					>
						Cancel
					</button>
					<button 
						type="submit" 
						class="px-4 py-2 text-sm font-medium rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
						disabled={!newPlaylistName.trim()}
					>
						Create
					</button>
				</div>
			</form>
		</div>
	{/if}

	{#if isLoading}
		<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
			{#each Array(4) as _}
				<div class="bg-card border rounded-xl overflow-hidden animate-pulse">
					<div class="aspect-video bg-muted w-full"></div>
					<div class="p-4 space-y-3">
						<div class="h-5 bg-muted rounded w-3/4"></div>
						<div class="h-4 bg-muted rounded w-1/2"></div>
					</div>
				</div>
			{/each}
		</div>
	{:else if error}
		<div class="flex flex-col items-center justify-center py-12 text-center">
			<div class="rounded-xl bg-red-100 p-4 text-red-600 dark:bg-red-900/30 dark:text-red-400">
				<p>{error}</p>
			</div>
		</div>
	{:else if playlists.length === 0}
		<div class="border-muted-foreground/20 flex flex-col items-center justify-center rounded-2xl border-2 border-dashed py-24 text-center">
			<ListVideo class="text-muted-foreground mb-4 h-12 w-12 opacity-50" />
			<h2 class="mb-2 text-xl font-semibold">No playlists yet</h2>
			<p class="text-muted-foreground max-w-sm">
				Create a playlist to organize your favorite videos.
			</p>
			<button 
				onclick={() => isCreating = true}
				class="mt-6 text-primary hover:underline font-medium"
			>
				Create one now
			</button>
		</div>
	{:else}
		<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
			{#each playlists as playlist}
				<div class="group relative bg-card border rounded-xl overflow-hidden hover:shadow-md transition-all">
					<a href={`/playlist/${playlist.id}`} class="block aspect-video bg-muted relative overflow-hidden">
						<!-- Display a grid of thumbnails if there are videos, or a placeholder -->
						<div class="absolute inset-0 flex items-center justify-center bg-secondary">
							<ListVideo class="w-12 h-12 text-muted-foreground/50" />
						</div>
						
						<div class="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
							<div class="flex items-center gap-2 text-white font-medium">
								<ListVideo class="w-5 h-5" />
								<span>Play All</span>
							</div>
						</div>
					</a>
					<div class="p-4 flex items-start justify-between">
						<div>
							<a href={`/playlist/${playlist.id}`} class="font-semibold text-lg line-clamp-1 hover:text-primary transition-colors">
								{playlist.title}
							</a>
							<p class="text-sm text-muted-foreground mt-1">
								{playlist.videoCount || 0} videos
							</p>
						</div>
						<button 
							onclick={() => handleDelete(playlist.id)}
							class="text-muted-foreground hover:text-red-500 transition-colors p-1"
							title="Delete Playlist"
						>
							<Trash2 class="w-4 h-4" />
						</button>
					</div>
				</div>
			{/each}
		</div>
	{/if}
</div>

// src/app/my-playlists/page.jsx
"use client";

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useSession } from 'next-auth/react';
import API from '@/lib/api';
import { toast } from 'react-toastify';
import EditPlaylistModal from '@/components/EditPlaylistModal';
import { FaGlobeAsia, FaLock, FaTrash } from 'react-icons/fa';

const MyPlaylistsPage = () => {
    const [playlists, setPlaylists] = useState([]);
    const [loading, setLoading] = useState(true);
    const [editingPlaylist, setEditingPlaylist] = useState(null);
    const { data: session, status } = useSession();
    const router = useRouter();

    useEffect(() => {
        if (status === 'unauthenticated') {
            router.push('/login');
            return;
        }
        if (status === 'authenticated') {
            const fetchPlaylists = async () => {
                try {
                    setLoading(true);
                    const response = await API.get('/playlists/my-playlists');
                    setPlaylists(response.data);
                } catch (error) {
                    toast.error("Failed to load playlists.");
                } finally {
                    setLoading(false);
                }
            };
            fetchPlaylists();
        }
    }, [status, router]);

    const handleCreatePlaylist = async (e) => {
        e.preventDefault();
        const title = e.target.title.value;
        if (!title.trim()) return;
        try {
            const response = await API.post('/playlists/my-playlists', { title, isPublic: true });
            setPlaylists(prev => [response.data, ...prev]);
            e.target.reset();
            toast.success("Playlist created!");
        } catch (error) { 
            toast.error("Failed to create playlist."); 
        }
    };
    
    const handleDeletePlaylist = async (playlistId) => {
        if (!window.confirm("Are you sure you want to delete this playlist?")) return;
        try {
            await API.delete(`/playlist/${playlistId}`);
            setPlaylists(prev => prev.filter(p => p._id !== playlistId));
            toast.success("Playlist deleted.");
        } catch (error) { 
            toast.error("Failed to delete playlist."); 
        }
    };

    const handleSaveEdit = async (playlistId, { title }) => {
        try {
            const response = await API.put('/playlists/my-playlists', { playlistId, title });
            setPlaylists(prev => prev.map(p => p._id === playlistId ? response.data : p));
            setEditingPlaylist(null);
            toast.success("Playlist updated!");
        } catch (error) {
            toast.error("Failed to update playlist.");
        }
    };
    
    const handlePrivacyToggle = async (playlist) => {
        try {
            const response = await API.put('/playlists/my-playlists', { playlistId: playlist._id, isPublic: !playlist.isPublic });
            setPlaylists(prev => prev.map(p => p._id === playlist._id ? response.data : p));
            toast.success("Privacy updated!");
        } catch (error) {
            toast.error("Failed to update privacy.");
        }
    };

    const handleShare = (playlistId) => {
        const url = `${window.location.origin}/playlist/${playlistId}`;
        navigator.clipboard.writeText(url).then(() => {
            toast.success("Playlist link copied to clipboard!");
        }).catch(err => {
            toast.error("Failed to copy link.");
            console.error('Failed to copy text: ', err);
        });
    };

    if (status === 'loading' || loading) {
        return (
            <main className="container mx-auto px-6 py-8 animate-pulse">
                <div className="h-10 bg-gray-300 rounded w-1/3 mb-6"></div>
                <div className="h-12 bg-gray-300 rounded-lg w-full mb-8"></div>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                    {Array.from({ length: 4 }).map((_, index) => (
                        <div key={index} className="bg-muted rounded-lg h-32"></div>
                    ))}
                </div>
            </main>
        );
    }

    return (
        <>
            {editingPlaylist && (
                <EditPlaylistModal
                    playlist={editingPlaylist}
                    onSave={handleSaveEdit}
                    onCancel={() => setEditingPlaylist(null)}
                />
            )}
            <main className="container mx-auto px-6 py-8">
                <h1 className="text-3xl font-extrabold text-foreground font-display tracking-tight mb-6">My Playlists</h1>
                
                <div className="mb-8 p-6 bg-muted/50 rounded-2xl border border-border shadow-sm transition-colors duration-300">
                    <form onSubmit={handleCreatePlaylist} className="flex flex-col sm:flex-row items-center gap-3">
                        <input name="title" type="text" placeholder="Create new playlist..." className="flex-grow w-full sm:w-auto px-4 py-2.5 border border-border rounded-xl bg-card text-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:border-border transition-all"/>
                        <button type="submit" className="w-full sm:w-auto px-6 py-2.5 bg-primary text-primary-foreground hover:bg-primary/90 text-primary-foreground text-primary-foreground rounded-xl font-semibold shadow-sm transition-colors">Create</button>
                    </form>
                </div>
                
                {playlists.length > 0 ? (
                    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                        {playlists.map(playlist => (
                            <div key={playlist._id} className="bg-card rounded-2xl shadow-md border border-border hover:border-border hover:shadow-lg p-5 group flex flex-col justify-between transition-all duration-300">
                                <div>
                                    <div className="flex items-start justify-between">
                                        <h2 className="text-xl font-bold text-foreground font-display tracking-tight truncate pr-2">{playlist.title}</h2>
                                        {playlist.isPublic ? (
                                            <FaGlobeAsia title="Public" className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                                        ) : (
                                            <FaLock title="Private" className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                                        )}
                                    </div>
                                    <p className="text-sm font-medium text-muted-foreground mt-1">{playlist.videos.length} videos</p>
                                </div>
                                <div className="mt-5 pt-3 border-t border-border flex items-center justify-between gap-2 flex-wrap">
                                    <Link href={`/playlist/${playlist._id}/edit`} className="text-xs font-semibold px-2.5 py-1 rounded-lg bg-muted text-primary hover:bg-muted0 transition-colors">Manage</Link>
                                    <div className="flex items-center space-x-2.5">
                                        <button onClick={() => handleShare(playlist._id)} className="text-xs font-medium text-muted-foreground hover:text-primary transition-colors">Share</button>
                                        <button onClick={() => handlePrivacyToggle(playlist)} className="text-xs font-medium text-muted-foreground hover:text-primary transition-colors">{playlist.isPublic ? 'Private' : 'Public'}</button>
                                        <button onClick={() => setEditingPlaylist(playlist)} className="text-xs font-medium text-muted-foreground hover:text-primary transition-colors">Rename</button>
                                        <button onClick={() => handleDeletePlaylist(playlist._id)} className="text-muted-foreground hover:text-rose-500 transition-colors p-1" title="Delete playlist">
                                            <FaTrash size={12} />
                                        </button>
                                    </div>
                                </div>
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="text-center p-12 border border-border bg-card rounded-2xl shadow-sm">
                        <h2 className="text-xl font-bold text-foreground">No playlists found</h2>
                        <p className="text-muted-foreground mt-2">Create your first playlist to get started.</p>
                    </div>
                )}
            </main>
        </>
    );
};

export default MyPlaylistsPage;
