// frontend/src/lib/components/EditVideoModal.svelte
<script lang="ts">
	import { Dialog, DialogContent, DialogHeader, DialogTitle } from '#lib/components/ui/dialog';
	import { Input } from '#lib/components/ui/input';
	import { Label } from '#lib/components/ui/label';
	import { Textarea } from '#lib/components/ui/textarea';
	import { Button } from '#lib/components/ui/button';
	import { fetchApi } from '#lib/api';
	import { createMutation, useQueryClient } from '@tanstack/svelte-query';
	import { Loader2, Image as ImageIcon } from 'lucide-svelte';

	let {
		video,
		open = $bindable(false),
		onClose
	} = $props<{ video: any; open: boolean; onClose?: () => void }>();

	const queryClient = useQueryClient();

	let title = $state('');
	let description = $state('');
	let category = $state('Other');
	let tags = $state('');
	let visibility = $state('public');
	let isAdult = $state(false);

	let thumbnailFile: File | null = $state(null);
	let error = $state('');

	// Sync local state when video prop changes or modal opens
	$effect(() => {
		if (open && video) {
			title = video.title || '';
			description = video.description || '';
			category = video.category || 'Other';
			tags = Array.isArray(video.tags) ? video.tags.join(', ') : '';
			visibility = video.visibility || 'public';
			isAdult = !!video.isAdult;
			thumbnailFile = null;
			error = '';
		}
	});

	const updateMutation = createMutation(
		() => ({
			mutationFn: async () => {
				// Update metadata
				const metaReq = fetchApi(`/videos/${video.id}`, {
					method: 'PUT',
					body: JSON.stringify({
						title,
						description,
						category,
						visibility,
						isAdult,
						tags: tags
							.split(',')
							.map((t) => t.trim())
							.filter(Boolean)
					})
				});

				// Update thumbnail if provided
				if (thumbnailFile) {
					const formData = new FormData();
					formData.append('thumbnailFile', thumbnailFile);
					const thumbReq = fetchApi(`/videos/${video.id}/update-thumbnail`, {
						method: 'POST',
						body: formData
					});
					await Promise.all([metaReq, thumbReq]);
				} else {
					await metaReq;
				}
			},
			onSuccess: () => {
				queryClient.invalidateQueries({ queryKey: ['dashboard'] });
				open = false;
				if (onClose) onClose();
			},
			onError: (err: any) => {
				error = err.message || 'Failed to update video';
			}
		}),
		() => queryClient
	);

	function handleSubmit(e: Event) {
		e.preventDefault();
		if (!title.trim()) {
			error = 'Title is required';
			return;
		}
		updateMutation.mutate();
	}
</script>

<Dialog bind:open>
	<DialogContent class="max-h-[90vh] overflow-y-auto sm:max-w-[600px]">
		<DialogHeader>
			<DialogTitle>Edit Video Details</DialogTitle>
		</DialogHeader>

		{#if error}
			<div class="bg-destructive/10 text-destructive rounded-lg p-3 text-sm font-medium">
				{error}
			</div>
		{/if}

		<form onsubmit={handleSubmit} class="space-y-5 py-4">
			<div class="space-y-1.5">
				<Label for="title">Title <span class="text-destructive">*</span></Label>
				<Input id="title" bind:value={title} required disabled={updateMutation.isPending} />
			</div>

			<div class="space-y-1.5">
				<Label for="description">Description</Label>
				<Textarea
					id="description"
					bind:value={description}
					rows={3}
					disabled={updateMutation.isPending}
				/>
			</div>

			<div class="grid grid-cols-2 gap-4">
				<div class="space-y-1.5">
					<Label for="category">Category</Label>
					<select
						id="category"
						bind:value={category}
						disabled={updateMutation.isPending}
						class="border-input h-10 w-full rounded-md border bg-background px-3 text-sm focus:ring-2 focus:ring-primary focus:outline-none disabled:opacity-50"
					>
						<option value="Other">Other</option>
						<option value="Gaming">Gaming</option>
						<option value="Education">Education</option>
						<option value="Entertainment">Entertainment</option>
						<option value="Music">Music</option>
						<option value="Science">Science & Tech</option>
					</select>
				</div>
				<div class="space-y-1.5">
					<Label for="visibility">Visibility</Label>
					<select
						id="visibility"
						bind:value={visibility}
						disabled={updateMutation.isPending}
						class="border-input h-10 w-full rounded-md border bg-background px-3 text-sm focus:ring-2 focus:ring-primary focus:outline-none disabled:opacity-50"
					>
						<option value="public">Public</option>
						<option value="unlisted">Unlisted</option>
						<option value="private">Private</option>
					</select>
				</div>
			</div>

			<div class="space-y-1.5">
				<Label for="tags">Tags (comma separated)</Label>
				<Input
					id="tags"
					bind:value={tags}
					placeholder="e.g. gaming, funny, stream"
					disabled={updateMutation.isPending}
				/>
			</div>

			<div class="space-y-1.5">
				<Label>Custom Thumbnail</Label>
				<div class="flex items-center gap-4">
					<input
						type="file"
						id="thumbnail"
						accept="image/*"
						class="hidden"
						onchange={(e) => {
							const target = e.target as HTMLInputElement;
							if (target.files?.length) thumbnailFile = target.files[0];
						}}
						disabled={updateMutation.isPending}
					/>
					<Button
						type="button"
						variant="outline"
						onclick={() => document.getElementById('thumbnail')?.click()}
						disabled={updateMutation.isPending}
					>
						<ImageIcon class="mr-2 h-4 w-4" />
						{thumbnailFile ? thumbnailFile.name : 'Choose Image'}
					</Button>
				</div>
			</div>

			<div class="flex items-center space-x-2 pt-2">
				<input
					type="checkbox"
					id="isAdult"
					bind:checked={isAdult}
					disabled={updateMutation.isPending}
					class="border-input h-4 w-4 rounded text-primary focus:ring-primary disabled:opacity-50"
				/>
				<Label for="isAdult" class="cursor-pointer">Contains Adult Content</Label>
			</div>

			<div class="flex justify-end gap-3 border-t pt-4">
				<Button
					type="button"
					variant="outline"
					onclick={() => (open = false)}
					disabled={updateMutation.isPending}
				>
					Cancel
				</Button>
				<Button type="submit" disabled={updateMutation.isPending}>
					{#if updateMutation.isPending}
						<Loader2 class="mr-2 h-4 w-4 animate-spin" /> Saving...
					{:else}
						Save Changes
					{/if}
				</Button>
			</div>
		</form>
	</DialogContent>
</Dialog>

// src/components/EditVideoModal.jsx
import React from "react";
import { useForm } from "react-hook-form";
import * as Yup from "yup";
import { yupResolver } from "@hookform/resolvers/yup";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import CATEGORIES from "@/constants/categories";

const editSchema = Yup.object().shape({
  title: Yup.string().required("Title is required"),
  description: Yup.string().optional(),
  tags: Yup.string().optional(),
  category: Yup.string().oneOf(CATEGORIES).required("Category is required"),
});

const EditVideoModal = ({ video, onSave, onCancel }) => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(editSchema),
    defaultValues: {
      title: video.title,
      description: video.description,
      tags: Array.isArray(video.tags) ? video.tags.join(", ") : "",
      category: video.category || "Other",
    },
  });

  const submitEdits = ({ tags, ...values }) => {
    const normalizedTags = [...new Set(
      tags.split(",").map((tag) => tag.trim()).filter(Boolean)
    )];
    onSave({ ...values, tags: normalizedTags });
  };

  return (
    <Dialog open={true} onOpenChange={(open) => !open && onCancel()}>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Edit Video Details</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit(submitEdits)} className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="title">Title</Label>
            <Input
              id="title"
              type="text"
              {...register("title")}
              className={errors.title ? "border-destructive focus-visible:ring-destructive" : ""}
            />
            {errors.title && (
              <p className="text-xs text-destructive mt-1">
                {errors.title.message}
              </p>
            )}
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="category">Category</Label>
            <select
              id="category"
              {...register("category")}
              className="flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
            >
              {CATEGORIES.map((category) => (
                <option key={category} value={category}>{category}</option>
              ))}
            </select>
            {errors.category && (
              <p className="text-xs text-destructive mt-1">{errors.category.message}</p>
            )}
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="tags">Tags</Label>
            <Input
              id="tags"
              type="text"
              placeholder="e.g., gaming, react, tutorial"
              {...register("tags")}
            />
            <p className="text-xs text-muted-foreground">Separate tags with commas.</p>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="description">
              Description <span className="text-xs text-muted-foreground font-normal">(Optional)</span>
            </Label>
            <Textarea
              id="description"
              rows={5}
              {...register("description")}
              className={`resize-none ${errors.description ? "border-destructive focus-visible:ring-destructive" : ""}`}
            />
            {errors.description && (
              <p className="text-xs text-destructive mt-1">
                {errors.description.message}
              </p>
            )}
          </div>
          <DialogFooter className="mt-8">
            <Button variant="ghost" type="button" onClick={onCancel}>
              Cancel
            </Button>
            <Button type="submit">
              Save Changes
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default EditVideoModal;
