// src/components/SaveToPlaylistModal.jsx
"use client";

import React, { useState, useEffect } from 'react';
import API from '@/lib/api';
import { toast } from 'react-toastify';

const SaveToPlaylistModal = ({ videoId, onClose }) => {
    const [playlists, setPlaylists] = useState([]);
    const [loading, setLoading] = useState(true);
    const [showCreateForm, setShowCreateForm] = useState(false);
    const [newPlaylistTitle, setNewPlaylistTitle] = useState("");
    const [newPlaylistIsPublic, setNewPlaylistIsPublic] = useState(true);

    useEffect(() => {
        const fetchPlaylists = async () => {
            try {
                const response = await API.get('/playlists');
                setPlaylists(response.data);
            } catch (error) {
                console.error("Failed to fetch playlists:", error);
            } finally {
                setLoading(false);
            }
        };
        fetchPlaylists();
    }, []);

    const handleToggleVideoInPlaylist = async (playlistId) => {
        try {
            const response = await API.put('/playlists', { playlistId, videoId });
            setPlaylists(prev => prev.map(p => p._id === playlistId ? response.data : p));
        } catch (error) {
            toast.error("Failed to update playlist.");
        }
    };
    
    const handleCreatePlaylist = async (e) => {
        e.preventDefault();
        if (!newPlaylistTitle.trim()) return;
        try {
            const response = await API.post('/playlists', { 
                title: newPlaylistTitle, 
                isPublic: newPlaylistIsPublic 
            });
            setPlaylists([...playlists, response.data]);
            setNewPlaylistTitle("");
            setShowCreateForm(false);
            toast.success("Playlist created!");
        } catch (error) {
            toast.error("Failed to create playlist.");
        }
    };

    return (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex justify-center items-center z-50 animate-in fade-in duration-200">
            <div className="bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-800 p-6 sm:p-8 rounded-2xl shadow-xl w-full max-w-sm">
                <div className="flex justify-between items-center mb-6">
                    <h2 className="text-xl font-bold text-gray-900 dark:text-gray-100">Save to...</h2>
                    <button onClick={onClose} className="text-3xl font-light text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 transition-colors leading-none">&times;</button>
                </div>
                {loading ? <p className="text-gray-500 dark:text-gray-400">Loading playlists...</p> : (
                    <ul className="space-y-2 max-h-60 overflow-y-auto pr-2">
                        {playlists.map(playlist => (
                            <li key={playlist._id}>
                                <label className="flex items-center space-x-3 cursor-pointer p-2 rounded-lg hover:bg-gray-50 dark:hover:bg-slate-800 transition-colors">
                                    <input 
                                        type="checkbox" 
                                        checked={playlist.videos.includes(videoId)}
                                        onChange={() => handleToggleVideoInPlaylist(playlist._id)}
                                        className="h-5 w-5 rounded text-indigo-600 focus:ring-indigo-500 border-gray-300 dark:border-slate-600 dark:bg-slate-700 transition-all cursor-pointer"
                                    />
                                    <span className="text-gray-700 dark:text-gray-300 font-medium">{playlist.title}</span>
                                </label>
                            </li>
                        ))}
                    </ul>
                )}
                <div className="mt-6 border-t border-gray-100 dark:border-slate-800 pt-6">
                    {showCreateForm ? (
                        <form onSubmit={handleCreatePlaylist} className="animate-in fade-in slide-in-from-top-2 duration-200">
                            <input 
                                type="text"
                                placeholder="Enter playlist name..."
                                value={newPlaylistTitle}
                                onChange={(e) => setNewPlaylistTitle(e.target.value)}
                                className="w-full px-4 py-2 bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 rounded-xl text-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 dark:text-white transition-all outline-none"
                                required
                            />
                            <div className="mt-4 flex items-center justify-between">
                                <label htmlFor="isPublic" className="text-sm text-gray-600 dark:text-gray-400 flex items-center gap-2 cursor-pointer font-medium">
                                    <input 
                                        id="isPublic"
                                        type="checkbox" 
                                        checked={newPlaylistIsPublic}
                                        onChange={(e) => setNewPlaylistIsPublic(e.target.checked)}
                                        className="h-4 w-4 rounded text-indigo-600 focus:ring-indigo-500 border-gray-300 dark:border-slate-600 dark:bg-slate-700 transition-all cursor-pointer"
                                    />
                                    Public
                                </label>
                                <div className="flex justify-end space-x-2">
                                    <button type="button" onClick={() => setShowCreateForm(false)} className="px-4 py-1.5 text-sm font-semibold bg-gray-100 dark:bg-slate-800 text-gray-700 dark:text-gray-300 rounded-full hover:bg-gray-200 dark:hover:bg-slate-700 transition-colors">Cancel</button>
                                    <button type="submit" className="px-4 py-1.5 text-sm font-semibold bg-indigo-600 text-white rounded-full hover:bg-indigo-700 transition-colors shadow-sm">Create</button>
                                </div>
                            </div>
                        </form>
                    ) : (
                        <button onClick={() => setShowCreateForm(true)} className="w-full text-left font-semibold text-indigo-600 dark:text-indigo-400 p-2 rounded-lg hover:bg-indigo-50 dark:hover:bg-slate-800 transition-colors">
                            + Create new playlist
                        </button>
                    )}
                </div>
            </div>
        </div>
    );
};

export default SaveToPlaylistModal;

// frontend/src/lib/components/SaveToPlaylistModal.svelte
<script lang="ts">
	import { fetchApi } from '#lib/api';
	import { Plus, X, ListVideo, Loader2, Check } from 'lucide-svelte';
	import { userState } from '#lib/user.svelte';
	import { onMount } from 'svelte';
	import { fade, scale } from 'svelte/transition';

	let { videoId, isOpen = $bindable(false) } = $props<{ videoId: string; isOpen: boolean }>();

	let playlists: any[] = $state([]);
	let isLoading = $state(true);
	let error = $state('');

	let isCreating = $state(false);
	let newPlaylistTitle = $state('');

	// State to track which playlists contain this video
	let savingStatus: Record<string, 'idle' | 'saving' | 'saved' | 'error'> = $state({});
	let containsVideo: Record<string, boolean> = $state({});

	$effect(() => {
		if (isOpen) {
			if (!userState.user) {
				alert('Please login to save to a playlist.');
				isOpen = false;
				return;
			}
			loadPlaylists();
		}
	});

	async function loadPlaylists() {
		isLoading = true;
		error = '';
		try {
			const res = await fetchApi('/playlists');
			playlists = res.playlists || res.data || [];

			// Check which playlists contain this video
			playlists.forEach(async (p) => {
				savingStatus[p.id] = 'idle';
				// Ideally, the backend would return this info in the /playlists list,
				// but if not, we can query the playlist details or just assume false
				// and let the toggle handle it. For a quick implementation, we will
				// assume false initially.
				containsVideo[p.id] = false;
			});
		} catch (err: any) {
			error = err.message || 'Failed to load playlists.';
		} finally {
			isLoading = false;
		}
	}

	async function handleToggle(playlist: any) {
		const pid = playlist.id;
		if (savingStatus[pid] === 'saving') return;
		savingStatus[pid] = 'saving';

		try {
			const action = containsVideo[pid] ? 'remove' : 'add';
			// Using the TogglePlaylistVideoHandler which is mapped to POST /playlists/:id/videos
			const res = await fetchApi(`/playlists/${pid}/videos`, {
				method: 'POST',
				body: JSON.stringify({ videoId, action })
			});
			containsVideo[pid] = action === 'add';
			savingStatus[pid] = 'saved';
			setTimeout(() => {
				if (savingStatus[pid] === 'saved') savingStatus[pid] = 'idle';
			}, 2000);
		} catch (err) {
			console.error(err);
			savingStatus[pid] = 'error';
			setTimeout(() => {
				if (savingStatus[pid] === 'error') savingStatus[pid] = 'idle';
			}, 2000);
		}
	}

	async function handleCreate() {
		if (!newPlaylistTitle.trim()) return;

		isCreating = true;
		try {
			const res = await fetchApi('/playlists', {
				method: 'POST',
				body: JSON.stringify({ title: newPlaylistTitle.trim(), isPublic: true })
			});

			const created = res.playlist;
			if (created) {
				playlists = [created, ...playlists];
				savingStatus[created.id] = 'idle';
				containsVideo[created.id] = false;

				// Automatically add to the new playlist
				await handleToggle(created);
			}
			newPlaylistTitle = '';
		} catch (err: any) {
			alert('Failed to create playlist');
		} finally {
			isCreating = false;
		}
	}
</script>

{#if isOpen}
	<div
		class="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm"
		transition:fade={{ duration: 200 }}
		role="dialog"
		aria-modal="true"
	>
		<div
			class="bg-card flex max-h-[85vh] w-full max-w-md flex-col overflow-hidden rounded-2xl border border-border shadow-2xl"
			transition:scale={{ duration: 200, start: 0.95 }}
		>
			<div class="bg-card sticky top-0 z-10 flex items-center justify-between border-b px-6 py-4">
				<h2 class="text-xl font-semibold tracking-tight">Save to playlist</h2>
				<button
					onclick={() => (isOpen = false)}
					class="hover:bg-muted text-muted-foreground hover:text-foreground -mr-2 rounded-full p-2 transition-colors"
				>
					<X class="h-5 w-5" />
				</button>
			</div>

			<div class="custom-scrollbar flex-1 overflow-y-auto p-6">
				{#if isLoading}
					<div class="flex items-center justify-center py-8">
						<Loader2 class="h-8 w-8 animate-spin text-primary" />
					</div>
				{:else if error}
					<div class="py-8 text-center font-medium text-rose-500">{error}</div>
				{:else}
					<div class="mb-6 space-y-2">
						{#each playlists as playlist}
							<button
								onclick={() => handleToggle(playlist)}
								class="hover:bg-muted/50 group flex w-full items-center justify-between rounded-xl p-3 text-left transition-colors"
							>
								<div class="flex items-center gap-3">
									<div
										class={`flex h-5 w-5 items-center justify-center rounded border transition-colors ${containsVideo[playlist.id] ? 'border-primary bg-primary' : 'border-muted-foreground/40 group-hover:border-foreground/60'}`}
									>
										{#if containsVideo[playlist.id]}
											<Check class="text-primary-foreground h-3.5 w-3.5" />
										{/if}
									</div>
									<span class="max-w-[200px] truncate font-medium sm:max-w-[260px]"
										>{playlist.title}</span
									>
								</div>

								{#if savingStatus[playlist.id] === 'saving'}
									<Loader2 class="text-muted-foreground h-4 w-4 animate-spin" />
								{:else if savingStatus[playlist.id] === 'error'}
									<span class="text-xs font-medium text-rose-500">Failed</span>
								{/if}
							</button>
						{:else}
							<div class="text-muted-foreground flex flex-col items-center py-6 text-center">
								<ListVideo class="mb-2 h-8 w-8 opacity-50" />
								<p>You don't have any playlists yet.</p>
							</div>
						{/each}
					</div>
				{/if}
			</div>

			<div class="bg-muted/20 border-t p-6">
				<form
					onsubmit={(e) => {
						e.preventDefault();
						handleCreate();
					}}
					class="flex gap-2"
				>
					<input
						type="text"
						bind:value={newPlaylistTitle}
						placeholder="New playlist name..."
						class="flex-1 rounded-xl border border-border bg-background px-4 py-2 text-sm transition-shadow focus:ring-2 focus:ring-primary focus:outline-none"
						required
					/>
					<button
						type="submit"
						disabled={isCreating || !newPlaylistTitle.trim()}
						class="bg-foreground hover:bg-foreground/90 flex shrink-0 items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold text-background transition-colors disabled:opacity-50"
					>
						{#if isCreating}
							<Loader2 class="h-4 w-4 animate-spin" />
						{:else}
							<Plus class="h-4 w-4" /> Create
						{/if}
					</button>
				</form>
			</div>
		</div>
	</div>
{/if}
