// frontend/src/routes/login/+page.svelte
<script lang="ts">
	import { Mail, Lock, ArrowRight, Loader2, Play } from 'lucide-svelte';
	import { fetchApi } from '#lib/api';
	import { createMutation } from '@tanstack/svelte-query';
	import { z } from 'zod';
	import { Button } from '#lib/components/ui/button';
	import { Input } from '#lib/components/ui/input';
	import { Label } from '#lib/components/ui/label';
	import * as Card from '#lib/components/ui/card';

	const loginSchema = z.object({
		email: z.string().email('Please enter a valid email address.'),
		password: z.string().min(1, 'Password is required.')
	});

	let email = $state('');
	let password = $state('');
	let validationErrors = $state<{ email?: string; password?: string }>({});

	const loginMutation = createMutation(() => ({
		mutationFn: async (data: z.infer<typeof loginSchema>) => {
			return await fetchApi('/auth/login', {
				method: 'POST',
				body: JSON.stringify(data)
			});
		},
		onSuccess: () => {
			window.location.href = '/';
		}
	}));

	function handleLogin(e: Event) {
		e.preventDefault();
		validationErrors = {};

		const result = loginSchema.safeParse({ email, password });
		if (!result.success) {
			const errors: Record<string, string> = {};
			for (const err of result.error.errors) {
				if (err.path[0]) {
					errors[err.path[0].toString()] = err.message;
				}
			}
			validationErrors = errors;
			return;
		}

		loginMutation.mutate(result.data);
	}
</script>

<div class="mx-auto mt-12 w-full max-w-md px-4 md:mt-24">
	<Card.Root class="border-border shadow-sm">
		<Card.Header class="items-center space-y-1 pb-8">
			<div class="text-primary-foreground mb-4 rounded-xl bg-primary p-3">
				<Play class="h-7 w-7 fill-current" />
			</div>
			<Card.Title class="text-center text-2xl font-bold tracking-tight">Welcome back</Card.Title>
			<Card.Description class="text-center"
				>Enter your credentials to access your account</Card.Description
			>
		</Card.Header>

		<Card.Content>
			{#if loginMutation.isError}
				<div
					class="bg-destructive/10 text-destructive mb-6 rounded-md p-3 text-center text-sm font-medium"
				>
					{loginMutation.error.message || 'Login failed. Please try again.'}
				</div>
			{/if}

			<form onsubmit={handleLogin} class="space-y-4">
				<div class="space-y-2">
					<Label for="email">Email address</Label>
					<div class="relative">
						<Mail class="text-muted-foreground absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2" />
						<Input
							id="email"
							type="email"
							bind:value={email}
							placeholder="name@example.com"
							class="pl-10 {validationErrors.email
								? 'border-destructive focus-visible:ring-destructive'
								: ''}"
						/>
					</div>
					{#if validationErrors.email}
						<p class="text-destructive text-xs font-medium">{validationErrors.email}</p>
					{/if}
				</div>

				<div class="space-y-2">
					<div class="flex items-center justify-between">
						<Label for="password">Password</Label>
						<a href="/forgot-password" class="text-xs font-medium text-primary hover:underline"
							>Forgot password?</a
						>
					</div>
					<div class="relative">
						<Lock class="text-muted-foreground absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2" />
						<Input
							id="password"
							type="password"
							bind:value={password}
							placeholder="••••••••"
							class="pl-10 {validationErrors.password
								? 'border-destructive focus-visible:ring-destructive'
								: ''}"
						/>
					</div>
					{#if validationErrors.password}
						<p class="text-destructive text-xs font-medium">{validationErrors.password}</p>
					{/if}
				</div>

				<Button type="submit" disabled={loginMutation.isPending} class="mt-6 w-full">
					{#if loginMutation.isPending}
						<Loader2 class="mr-2 -ml-1 h-4 w-4 animate-spin" />
						Signing in...
					{:else}
						Sign In
						<ArrowRight class="ml-2 h-4 w-4" />
					{/if}
				</Button>
			</form>
		</Card.Content>

		<Card.Footer class="flex justify-center border-t p-6">
			<div class="text-sm">
				<span class="text-muted-foreground">Don't have an account? </span>
				<a href="/signup" class="font-medium text-primary hover:underline">Sign up now</a>
			</div>
		</Card.Footer>
	</Card.Root>
</div>

// legacy/src/app/login/page.jsx
"use client";

import React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as Yup from "yup";
import { toast } from "react-toastify";
import { FaGoogle, FaGithub } from "react-icons/fa";

const loginSchema = Yup.object().shape({
  email: Yup.string()
    .email("Please enter a valid email address")
    .required("Email is required"),
  password: Yup.string().required("Password is required"),
});

const LoginPage = () => {
  const router = useRouter();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(loginSchema),
  });

  const onSubmit = async (data) => {
    const result = await signIn('credentials', {
      redirect: false,
      email: data.email,
      password: data.password,
    });

    if (result.error) {
      toast.error("Invalid email or password.");
    } else {
      toast.success("Logged in successfully!");
      router.push("/");
    }
  };

  const handleSocialLogin = (provider) => {
    signIn(provider, { callbackUrl: '/' });
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-muted/50 transition-colors duration-300 px-4">
      <div className="w-full max-w-md p-8 space-y-6 bg-card rounded-2xl shadow-xl border border-border animate-in fade-in duration-300">
        <div className="text-center">
          <h1 className="text-3xl font-bold text-foreground">Sign In</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            Welcome back! Please enter your details.
          </p>
        </div>

        <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}>
          <div>
            <label
              htmlFor="email"
              className="text-sm font-medium text-muted-foreground"
            >
              Email address
            </label>
            <input
              id="email"
              type="email"
              {...register("email")}
              className={`w-full px-4 py-2 mt-1 border rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-ring focus:border-border bg-card  text-foreground  transition-all ${
                errors.email ? "border-rose-500" : "border-border "
              }`}
            />
            {errors.email && (
              <p className="mt-1 text-xs text-red-600">
                {errors.email.message}
              </p>
            )}
          </div>
          <div>
            <label
              htmlFor="password"
              className="text-sm font-medium text-muted-foreground"
            >
              Password
            </label>
            <input
              id="password"
              type="password"
              {...register("password")}
              className={`w-full px-4 py-2 mt-1 border rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-ring focus:border-border bg-card  text-foreground  transition-all ${
                errors.password ? "border-rose-500" : "border-border "
              }`}
            />
            {errors.password && (
              <p className="mt-1 text-xs text-red-600">
                {errors.password.message}
              </p>
            )}
          </div>
          <div>
            <button
              type="submit"
              className="w-full px-4 py-2.5 text-sm font-semibold text-primary-foreground bg-primary text-primary-foreground rounded-xl shadow-sm hover:bg-primary/90 text-primary-foreground transition-colors"
            >
              Sign In
            </button>
          </div>
        </form>

        <div className="my-4 flex items-center before:flex-1 before:border-t before:border-border dark:before:border-border after:flex-1 after:border-t after:border-border dark:after:border-border">
            <p className="mx-4 text-center font-semibold text-muted-foreground text-xs tracking-wider">OR</p>
        </div>
        
        <div className="space-y-3">
            <button type="button" onClick={() => handleSocialLogin('google')} className="flex w-full items-center justify-center gap-3 rounded-xl bg-card px-4 py-2.5 text-sm font-semibold text-muted-foreground border border-border shadow-sm hover:bg-muted/50 transition-colors">
                <FaGoogle className="h-5 w-5 text-rose-500" />
                Continue with Google
            </button>
            <button type="button" onClick={() => handleSocialLogin('github')} className="flex w-full items-center justify-center gap-3 rounded-xl bg-background px-4 py-2.5 text-sm font-semibold text-primary-foreground shadow-sm hover:bg-muted transition-colors">
                <FaGithub className="h-5 w-5" />
                Continue with GitHub
            </button>
        </div>

        <p className="text-sm text-center text-muted-foreground">
          Don&apos;t have an account?{" "}
          <Link
            href="/register"
            className="font-semibold text-primary hover:text-primary transition-colors"
          >
            Sign Up
          </Link>
        </p>
      </div>
    </div>
  );
};

export default LoginPage;
