// frontend/src/routes/register/+page.svelte
<script lang="ts">
    import { Mail, Lock, User, ArrowRight } from 'lucide-svelte';

    let username = $state('');
    let email = $state('');
    let password = $state('');
    let loading = $state(false);

    async function handleRegister(e: Event) {
        e.preventDefault();
        loading = true;
        // Mock request to our Go backend
        setTimeout(() => {
            loading = false;
        }, 1000);
    }
</script>

<div class="min-h-[80vh] flex items-center justify-center p-4">
    <div class="w-full max-w-md glass-card p-8 flex flex-col gap-6 relative overflow-hidden shadow-2xl shadow-black/5 dark:shadow-white/5">
        <div class="absolute -top-24 -left-24 w-48 h-48 bg-primary opacity-5 rounded-full blur-3xl pointer-events-none"></div>

        <div class="flex flex-col gap-2 relative z-10 text-center">
            <h1 class="text-3xl font-bold text-text-main tracking-tight">Create Account</h1>
            <p class="text-text-muted text-sm">Join Aurahub to upload and interact with videos</p>
        </div>

        <form onsubmit={handleRegister} class="flex flex-col gap-4 relative z-10 mt-2">
            <div class="space-y-1.5">
                <label for="username" class="text-sm font-medium text-text-main">Username</label>
                <div class="relative group">
                    <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <User class="h-5 w-5 text-text-muted group-focus-within:text-primary transition-colors" />
                    </div>
                    <input 
                        id="username" 
                        type="text" 
                        bind:value={username}
                        required
                        class="block w-full pl-10 pr-4 py-2.5 border border-border rounded-xl bg-surface/50 text-text-main placeholder-text-muted focus:ring-1 focus:ring-primary focus:border-primary focus:bg-surface focus:outline-none transition-all duration-300"
                        placeholder="coolcreator99"
                    >
                </div>
            </div>

            <div class="space-y-1.5">
                <label for="email" class="text-sm font-medium text-text-main">Email</label>
                <div class="relative group">
                    <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <Mail class="h-5 w-5 text-text-muted group-focus-within:text-primary transition-colors" />
                    </div>
                    <input 
                        id="email" 
                        type="email" 
                        bind:value={email}
                        required
                        class="block w-full pl-10 pr-4 py-2.5 border border-border rounded-xl bg-surface/50 text-text-main placeholder-text-muted focus:ring-1 focus:ring-primary focus:border-primary focus:bg-surface focus:outline-none transition-all duration-300"
                        placeholder="you@example.com"
                    >
                </div>
            </div>

            <div class="space-y-1.5">
                <label for="password" class="text-sm font-medium text-text-main">Password</label>
                <div class="relative group">
                    <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <Lock class="h-5 w-5 text-text-muted group-focus-within:text-primary transition-colors" />
                    </div>
                    <input 
                        id="password" 
                        type="password" 
                        bind:value={password}
                        required
                        class="block w-full pl-10 pr-4 py-2.5 border border-border rounded-xl bg-surface/50 text-text-main placeholder-text-muted focus:ring-1 focus:ring-primary focus:border-primary focus:bg-surface focus:outline-none transition-all duration-300"
                        placeholder="••••••••"
                    >
                </div>
            </div>

            <button 
                type="submit" 
                disabled={loading}
                class="mt-4 w-full flex items-center justify-center gap-2 bg-primary text-background hover:bg-primary-hover px-4 py-3 rounded-xl font-medium transition-all duration-300 disabled:opacity-70 disabled:cursor-not-allowed group shadow-md"
            >
                {#if loading}
                    <div class="w-5 h-5 border-2 border-background border-t-transparent rounded-full animate-spin"></div>
                    <span>Creating account...</span>
                {:else}
                    <span>Sign Up</span>
                    <ArrowRight class="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                {/if}
            </button>
        </form>

        <p class="text-center text-sm text-text-muted mt-2">
            Already have an account? <a href="/login" class="text-text-main font-medium hover:underline transition-all">Sign in</a>
        </p>
    </div>
</div>

// src/app/register/page.jsx
"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import * as Yup from "yup";
import { toast } from "react-toastify";
import API from "@/lib/api";
import axios from "axios";
import { signIn } from "next-auth/react";
import { useDebounce } from "@/hooks/useDebounce";
import { FaCheckCircle, FaTimesCircle, FaSpinner } from "react-icons/fa";
import PasswordStrength from "@/components/PasswordStrength";

const registerSchema = Yup.object().shape({
  username: Yup.string()
    .required("Username is required")
    .min(3, "Username must be at least 3 characters"),
  email: Yup.string()
    .email("Invalid email format")
    .required("Email is required"),
  password: Yup.string()
    .required("Password is required")
    .min(8, "Password must be at least 8 characters")
    .matches(
      /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])/,
      "Must meet all strength requirements"
    ),
  confirmPassword: Yup.string()
    .oneOf([Yup.ref("password"), null], "Passwords must match")
    .required("Please confirm your password"),
  avatar: Yup.mixed().test(
    "fileSize",
    "The file is too large (max 5MB)",
    (value) => {
      if (!value || !value.length) return true;
      return value[0].size <= 5000000;
    }
  ),
});

const RegisterPage = () => {
  const router = useRouter();
  const [usernameStatus, setUsernameStatus] = useState({
    loading: false,
    message: "",
  });
  const [emailStatus, setEmailStatus] = useState({
    loading: false,
    message: "",
  });
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showPassword, setShowPassword] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
    watch,
  } = useForm({
    resolver: yupResolver(registerSchema),
    mode: "onChange",
  });

  const usernameValue = watch("username");
  const emailValue = watch("email");
  const passwordValue = watch("password", "");

  const debouncedUsername = useDebounce(usernameValue, 2000);
  const debouncedEmail = useDebounce(emailValue, 2000);

  useEffect(() => {
    if (!debouncedUsername || errors.username) {
      setUsernameStatus({ loading: false, message: "" });
      return;
    }
    const checkUsername = async () => {
      setUsernameStatus({ loading: true, message: "" });
      try {
        const res = await API.post("/auth/check-username", {
          username: debouncedUsername,
        });
        setUsernameStatus({
          loading: false,
          message: res.data.available
            ? "Username is available!"
            : res.data.message,
        });
      } catch (err) {
        setUsernameStatus({
          loading: false,
          message: err.response?.data?.message || "Error checking username.",
        });
      }
    };
    checkUsername();
  }, [debouncedUsername, errors.username]);

  useEffect(() => {
    if (!debouncedEmail || errors.email) {
      setEmailStatus({ loading: false, message: "" });
      return;
    }
    const checkEmail = async () => {
      setEmailStatus({ loading: true, message: "" });
      try {
        const res = await API.post("/auth/check-email", {
          email: debouncedEmail,
        });
        setEmailStatus({
          loading: false,
          message: res.data.available
            ? "Email is available!"
            : res.data.message,
        });
      } catch (err) {
        setEmailStatus({
          loading: false,
          message: err.response?.data?.message || "Error checking email.",
        });
      }
    };
    checkEmail();
  }, [debouncedEmail, errors.email]);

  const onSubmit = async (data) => {
    setIsSubmitting(true);
    try {
      let avatarUrl = null;
      if (data.avatar && data.avatar.length > 0) {
        const formData = new FormData();
        formData.append("avatar", data.avatar[0]);
        const response = await axios.post("/api/upload/avatar", formData);
        avatarUrl = response.data.url;
      }

      await API.post("/auth/register", {
        username: data.username,
        email: data.email,
        password: data.password,
        avatar: avatarUrl,
      });

      const result = await signIn("credentials", {
        redirect: false,
        email: data.email,
        password: data.password,
      });

      if (result.error) {
        toast.error("Login failed after registration.");
      } else {
        toast.success("Registration successful! Welcome.");
        router.push("/");
      }
    } catch (err) {
      toast.error(err.response?.data?.message || "Registration failed.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="flex items-center justify-center min-h-screen bg-muted/50 transition-colors duration-300 px-4 py-12">
      <div className="w-full max-w-md p-8 space-y-6 bg-card rounded-2xl shadow-xl border border-border animate-in fade-in duration-300">
        <h1 className="text-3xl font-bold text-center text-foreground">Create an Account</h1>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div>
            <label
              htmlFor="username"
              className="block text-sm font-medium text-muted-foreground"
            >
              Username
            </label>
            <div className="relative mt-1">
              <input
                id="username"
                {...register("username")}
                className={`w-full px-4 py-2 border rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-ring focus:border-border pr-10 bg-card  text-foreground  transition-all ${
                  errors.username ? "border-rose-500" : "border-border "
                }`}
              />
              <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                {usernameStatus.loading && (
                  <FaSpinner className="animate-spin text-muted-foreground" />
                )}
                {usernameStatus.message === "Username is available!" && (
                  <FaCheckCircle className="text-emerald-500" />
                )}
                {usernameStatus.message &&
                  usernameStatus.message !== "Username is available!" &&
                  !errors.username && (
                    <FaTimesCircle className="text-rose-500" />
                  )}
              </div>
            </div>
            {errors.username ? (
              <p className="text-xs text-rose-600 mt-1">
                {errors.username.message}
              </p>
            ) : (
              <p
                className={`text-xs mt-1 h-4 ${
                  usernameStatus.message === "Username is available!"
                    ? "text-emerald-600 "
                    : "text-rose-600 "
                }`}
              >
                {usernameStatus.message}
              </p>
            )}
          </div>
          <div>
            <label
              htmlFor="email"
              className="block text-sm font-medium text-muted-foreground"
            >
              Email
            </label>
            <div className="relative mt-1">
              <input
                id="email"
                type="email"
                {...register("email")}
                className={`w-full px-4 py-2 border rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-ring focus:border-border pr-10 bg-card  text-foreground  transition-all ${
                  errors.email ? "border-rose-500" : "border-border "
                }`}
              />
              <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none">
                {emailStatus.loading && (
                  <FaSpinner className="animate-spin text-muted-foreground" />
                )}
                {emailStatus.message === "Email is available!" && (
                  <FaCheckCircle className="text-emerald-500" />
                )}
                {emailStatus.message &&
                  emailStatus.message !== "Email is available!" &&
                  !errors.email && <FaTimesCircle className="text-rose-500" />}
              </div>
            </div>
            {errors.email ? (
              <p className="text-xs text-rose-600 mt-1">
                {errors.email.message}
              </p>
            ) : (
              <p
                className={`text-xs mt-1 h-4 ${
                  emailStatus.message === "Email is available!"
                    ? "text-emerald-600 "
                    : "text-rose-600 "
                }`}
              >
                {emailStatus.message}
              </p>
            )}
          </div>
          <div>
            <label
              htmlFor="password"
              className="block text-sm font-medium text-muted-foreground"
            >
              Password
            </label>
            <div className="relative mt-1">
              <input
                id="password"
                type={showPassword ? "text" : "password"}
                {...register("password")}
                className={`w-full px-4 py-2 border rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-ring focus:border-border pr-10 bg-card  text-foreground  transition-all ${
                  errors.password ? "border-rose-500" : "border-border "
                }`}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute inset-y-0 right-0 flex items-center pr-3 text-xl"
              >
                {showPassword ? "🙉" : "🙈"}
              </button>
            </div>
            <PasswordStrength password={passwordValue || ""} />
            {errors.password && (
              <p className="text-xs text-rose-600 mt-1">
                {errors.password.message}
              </p>
            )}
          </div>
          <div>
            <label
              htmlFor="confirmPassword"
              className="block text-sm font-medium text-muted-foreground"
            >
              Confirm Password
            </label>
            <div className="relative mt-1">
              <input
                id="confirmPassword"
                type={showPassword ? "text" : "password"}
                {...register("confirmPassword")}
                className={`w-full px-4 py-2 border rounded-xl shadow-sm focus:outline-none focus:ring-2 focus:ring-ring focus:border-border pr-10 bg-card  text-foreground  transition-all ${
                  errors.confirmPassword ? "border-rose-500" : "border-border "
                }`}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute inset-y-0 right-0 flex items-center pr-3 text-xl"
              >
                {showPassword ? "🙉" : "🙈"}
              </button>
            </div>
            {errors.confirmPassword && (
              <p className="text-xs text-rose-600 mt-1">
                {errors.confirmPassword.message}
              </p>
            )}
          </div>
          <div>
            <label className="block text-sm font-medium text-muted-foreground">
              Avatar (Optional)
            </label>
            <input
              type="file"
              accept="image/*"
              {...register("avatar")}
              className="w-full mt-1 text-sm text-muted-foreground file:mr-4 file:py-2.5 file:px-4 file:rounded-xl file:border-0 file:text-sm file:font-semibold file:bg-muted file:text-primary transition-all cursor-pointer"
            />
            {errors.avatar && (
              <p className="text-xs text-rose-600 mt-1">
                {errors.avatar.message}
              </p>
            )}
          </div>
          <button
            type="submit"
            disabled={isSubmitting}
            className="w-full px-4 py-2.5 text-sm font-semibold text-primary-foreground bg-primary border border-transparent rounded-xl shadow-sm hover:bg-primary/90 disabled:opacity-50 transition-colors"
          >
            {isSubmitting ? "Signing Up..." : "Sign Up"}
          </button>
        </form>
        <p className="text-sm text-center text-muted-foreground">
          Already have an account?{" "}
          <Link href="/login" className="font-semibold text-primary hover:text-primary transition-colors">
            Sign In
          </Link>
        </p>
      </div>
    </div>
  );
};

export default RegisterPage;
