// src/app/history/page.jsx
"use client";

import React, { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import API from "@/lib/api";
import Link from "next/link";
import VideoThumbnail from "@/components/VideoThumbnail";
import { toast } from "react-toastify";
import { MdDelete, MdAutoDelete } from "react-icons/md";

const HistoryPage = () => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const { data: session, status } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/login");
      return;
    }

    if (status === "authenticated") {
      const fetchHistory = async () => {
        try {
          setLoading(true);
          const response = await API.get("/user/history");
          setHistory(response.data);
        } catch (error) {
          console.error("Failed to fetch history:", error);
          toast.error("Could not load your watch history.");
        } finally {
          setLoading(false);
        }
      };
      fetchHistory();
    }
  }, [status, router]);

  const handleRemove = async (e, videoId) => {
    e.preventDefault();
    e.stopPropagation();
    try {
      await API.delete(`/user/history?videoId=${videoId}`);
      setHistory((prev) => prev.filter((item) => item.videoId._id !== videoId));
      toast.success("Removed from watch history.");
    } catch (error) {
      toast.error("Failed to remove video from history.");
    }
  };

  const handleClearAll = async () => {
    if (
      window.confirm(
        "Are you sure you want to clear your entire watch history? This action cannot be undone."
      )
    ) {
      try {
        await API.delete("/user/history");
        setHistory([]);
        toast.success("Watch history cleared.");
      } catch (error) {
        toast.error("Failed to clear history.");
      }
    }
  };

  if (status === "loading" || loading) {
    return (
      <div className="text-center p-10">Loading your watch history...</div>
    );
  }

  return (
    <main className="container mx-auto px-6 py-8">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-extrabold text-foreground font-display tracking-tight">Watch History</h1>
        {history.length > 0 && (
          <button
            onClick={handleClearAll}
            className="flex items-center gap-2 text-sm font-semibold text-rose-600 hover:text-rose-700 transition-colors"
          >
            Clear all <MdAutoDelete />
          </button>
        )}
      </div>

      <div className="space-y-4">
        {history.length > 0 ? (
          history.map(({ videoId: video, updatedAt }) => (
            <Link
              key={video._id}
              href={`/video/${video._id}`}
              className="flex items-center space-x-4 p-3 rounded-xl hover:bg-muted/50 border border-transparent hover:border-border transition-all group"
            >
              <div className="w-48 h-28 flex-shrink-0 shadow-sm group-hover:shadow-md transition-shadow rounded-xl overflow-hidden">
                <VideoThumbnail
                  videoId={video._id}
                  altText={video.title}
                  title={video.title}
                  category={video.category}
                  thumbnailUrl={video.thumbnailUrl}
                />
              </div>
              <div className="w-0 flex-grow">
                <h3 className="text-lg font-bold text-foreground font-display tracking-tight truncate mb-1">{video.title}</h3>
                <p className="text-sm font-medium text-muted-foreground truncate">
                  {video.uploader?.username}
                </p>
                <p className="text-xs text-muted-foreground mt-1">
                  Watched on {new Date(updatedAt).toLocaleDateString()}
                </p>
              </div>
              <button
                onClick={(e) => handleRemove(e, video._id)}
                className="p-2 text-muted-foreground transition-colors"
              >
                <MdDelete className="hover:text-rose-600 h-5 w-5" />
              </button>
            </Link>
          ))
        ) : (
          <div className="text-center p-12 border border-border bg-card rounded-2xl shadow-sm">
            <h2 className="text-xl font-bold text-foreground">No watch history</h2>
            <p className="text-muted-foreground mt-2">
              Videos you watch will appear here.
            </p>
          </div>
        )}
      </div>
    </main>
  );
};

export default HistoryPage;

// frontend/src/routes/history/+page.svelte
<script lang="ts">
	import { fetchApi } from '#lib/api';
	import VideoThumbnail from '#lib/components/VideoThumbnail.svelte';
	import WatchLaterButton from '#lib/components/WatchLaterButton.svelte';
	import { Clock, Trash2 } from 'lucide-svelte';
	import { createQuery, createMutation, useQueryClient } from '@tanstack/svelte-query';
	import { Skeleton } from '#lib/components/ui/skeleton';
	import { Button } from '#lib/components/ui/button';

	const queryClient = useQueryClient();

	const historyQuery = createQuery(
		() => ({
			queryKey: ['history'],
			queryFn: async () => {
				const res = await fetchApi('/user/history');
				return res.history || res.videos || res.items || res || [];
			}
		}),
		() => queryClient
	);

	const deleteHistoryMutation = createMutation(
		() => ({
			mutationFn: async (videoId: string) => {
				await fetchApi(`/user/history/${videoId}`, { method: 'DELETE' });
			},
			onSuccess: () => {
				queryClient.invalidateQueries({ queryKey: ['history'] });
			}
		}),
		() => queryClient
	);

	const clearHistoryMutation = createMutation(
		() => ({
			mutationFn: async () => {
				await fetchApi('/user/history', { method: 'DELETE' });
			},
			onSuccess: () => {
				queryClient.invalidateQueries({ queryKey: ['history'] });
			}
		}),
		() => queryClient
	);

	function handleDelete(e: Event, videoId: string) {
		e.preventDefault();
		e.stopPropagation();
		deleteHistoryMutation.mutate(videoId);
	}

	function handleClearAll() {
		if (confirm('Are you sure you want to clear your entire watch history?')) {
			clearHistoryMutation.mutate();
		}
	}

	function formatTimeAgo(dateString: string) {
		const date = new Date(dateString);
		const seconds = Math.floor((new Date().getTime() - date.getTime()) / 1000);
		let interval = seconds / 31536000;
		if (interval > 1) return Math.floor(interval) + ' years ago';
		interval = seconds / 2592000;
		if (interval > 1) return Math.floor(interval) + ' months ago';
		interval = seconds / 86400;
		if (interval > 1) return Math.floor(interval) + ' days ago';
		interval = seconds / 3600;
		if (interval > 1) return Math.floor(interval) + ' hours ago';
		interval = seconds / 60;
		if (interval > 1) return Math.floor(interval) + ' minutes ago';
		return Math.floor(seconds) + ' seconds ago';
	}
</script>

<svelte:head>
	<title>Watch History - Aurahub</title>
</svelte:head>

<div class="space-y-4 px-4 md:space-y-6 md:px-0">
	<div class="flex items-center justify-between border-b pt-2 pb-4 md:pt-0">
		<div class="flex items-center gap-3">
			<Clock class="h-6 w-6 text-primary" />
			<h1 class="text-xl font-bold tracking-tight md:text-2xl">Watch History</h1>
		</div>

		{#if historyQuery.data && historyQuery.data.length > 0}
			<Button
				variant="outline"
				size="sm"
				class="text-destructive hover:bg-destructive/10 hover:text-destructive"
				onclick={handleClearAll}
				disabled={clearHistoryMutation.isPending}
			>
				Clear All
			</Button>
		{/if}
	</div>

	{#if historyQuery.isPending}
		<div class="flex max-w-4xl flex-col gap-4">
			{#each Array(5) as _}
				<div class="flex animate-pulse flex-col gap-4 sm:flex-row">
					<Skeleton class="aspect-video w-full shrink-0 rounded-xl sm:w-64" />
					<div class="flex-1 space-y-3 py-2">
						<Skeleton class="h-5 w-3/4 rounded" />
						<Skeleton class="h-4 w-1/4 rounded" />
					</div>
				</div>
			{/each}
		</div>
	{:else if historyQuery.isError}
		<div class="flex flex-col items-center justify-center py-12 text-center">
			<div class="bg-destructive/10 text-destructive rounded-xl p-4">
				<p>{historyQuery.error.message || 'Failed to load history.'}</p>
				<Button variant="outline" class="mt-4" onclick={() => historyQuery.refetch()}
					>Try again</Button
				>
			</div>
		</div>
	{:else if !historyQuery.data || historyQuery.data.length === 0}
		<div
			class="border-muted-foreground/20 mx-4 flex flex-col items-center justify-center rounded-2xl border-2 border-dashed py-16 text-center md:mx-0 md:py-24"
		>
			<Clock class="text-muted-foreground mb-4 h-12 w-12 opacity-50" />
			<h2 class="mb-2 text-lg font-semibold md:text-xl">No watch history</h2>
			<p class="text-muted-foreground max-w-sm px-4 text-sm md:text-base">
				Videos you watch will show up here.
			</p>
			<Button variant="default" class="mt-6 rounded-full" href="/">Watch Videos</Button>
		</div>
	{:else}
		<div class="flex max-w-4xl flex-col gap-6 md:gap-4">
			{#each historyQuery.data as item}
				{@const video = item.video || item}
				<a
					href={`/watch/${video.fileId || video.id}`}
					class="group hover:bg-muted/50 flex flex-col gap-3 rounded-xl transition-colors sm:flex-row sm:p-2 md:gap-4"
				>
					<!-- Thumbnail -->
					<div class="w-full shrink-0 sm:w-64">
						<VideoThumbnail
							{video}
							class="aspect-video rounded-xl sm:rounded-lg"
							imgClass="transition-transform duration-300 group-hover:scale-105"
						>
							<WatchLaterButton videoId={video.id} />
						</VideoThumbnail>
					</div>
					<!-- Metadata -->
					<div class="relative flex flex-1 flex-col px-1 py-1 sm:px-0">
						<div class="pr-8">
							<h3
								class="mb-1 line-clamp-2 text-base leading-tight font-semibold transition-colors group-hover:text-primary md:text-lg"
							>
								{video.title}
							</h3>

							<div class="mb-1 flex items-center gap-2">
								<p class="text-[13px] font-medium transition-colors hover:text-primary md:text-sm">
									{video.uploader_username || video.uploader?.username}
								</p>
							</div>

							<div class="text-muted-foreground mb-3 text-[11px] md:text-xs">
								<span>{video.views || 0} views</span>
								<span class="mx-1">•</span>
								<span
									>Watched {formatTimeAgo(
										item.watchedAt || item.watched_at || new Date().toISOString()
									)}</span
								>
							</div>

							{#if video.description}
								<p
									class="text-muted-foreground line-clamp-1 text-[11px] md:line-clamp-2 md:text-xs"
								>
									{video.description}
								</p>
							{/if}
						</div>

						<Button
							variant="ghost"
							size="icon"
							class="text-muted-foreground hover:text-destructive hover:bg-destructive/10 absolute top-0 right-0 h-8 w-8 opacity-100 transition-opacity group-hover:opacity-100 md:opacity-0"
							onclick={(e) => handleDelete(e, video.id || video.fileId)}
							title="Remove from Watch History"
						>
							<Trash2 class="h-4 w-4" />
						</Button>
					</div>
				</a>
			{/each}
		</div>
	{/if}
</div>
